/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/design'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiWorkspacesRouteImport } from './routes/api/workspaces'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GroupsSlugRouteImport } from './routes/groups/$slug'
import { Route as GroupsNewRouteImport } from './routes/groups/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWorkspacesMembersRouteImport } from './routes/api/workspaces/members'
import { Route as GroupsSlugEventsRouteImport } from './routes/groups/$slug_.events'
import { Route as GroupsSlugRolesRouteImport } from './routes/groups/$slug_.roles'
import { Route as GroupsSlugEventsNewRouteImport } from './routes/groups/$slug_.events_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesRoute = ApiWorkspacesRouteImport.update({
  id: '/api/workspaces',
  path: '/api/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsSlugRoute = GroupsSlugRouteImport.update({
  id: '/groups/$slug',
  path: '/groups/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsNewRoute = GroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesMembersRoute = ApiWorkspacesMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiWorkspacesRoute,
} as any)
const GroupsSlugEventsRoute = GroupsSlugEventsRouteImport.update({
  id: '/groups/$slug_/events',
  path: '/groups/$slug/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsSlugRolesRoute = GroupsSlugRolesRouteImport.update({
  id: '/groups/$slug_/roles',
  path: '/groups/$slug/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsSlugEventsNewRoute = GroupsSlugEventsNewRouteImport.update({
  id: '/groups/$slug_/events_/new',
  path: '/groups/$slug/events/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/api/events': typeof ApiEventsRoute
  '/api/me': typeof ApiMeRoute
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/groups/$slug': typeof GroupsSlugRoute
  '/groups/new': typeof GroupsNewRoute
  '/groups/': typeof GroupsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/workspaces/members': typeof ApiWorkspacesMembersRoute
  '/groups/$slug/events': typeof GroupsSlugEventsRoute
  '/groups/$slug/roles': typeof GroupsSlugRolesRoute
  '/groups/$slug/events/new': typeof GroupsSlugEventsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/api/events': typeof ApiEventsRoute
  '/api/me': typeof ApiMeRoute
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/groups/$slug': typeof GroupsSlugRoute
  '/groups/new': typeof GroupsNewRoute
  '/groups': typeof GroupsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/workspaces/members': typeof ApiWorkspacesMembersRoute
  '/groups/$slug/events': typeof GroupsSlugEventsRoute
  '/groups/$slug/roles': typeof GroupsSlugRolesRoute
  '/groups/$slug/events/new': typeof GroupsSlugEventsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/api/events': typeof ApiEventsRoute
  '/api/me': typeof ApiMeRoute
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/groups/$slug': typeof GroupsSlugRoute
  '/groups/new': typeof GroupsNewRoute
  '/groups/': typeof GroupsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/workspaces/members': typeof ApiWorkspacesMembersRoute
  '/groups/$slug_/events': typeof GroupsSlugEventsRoute
  '/groups/$slug_/roles': typeof GroupsSlugRolesRoute
  '/groups/$slug_/events_/new': typeof GroupsSlugEventsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/home'
    | '/login'
    | '/api/events'
    | '/api/me'
    | '/api/workspaces'
    | '/groups/$slug'
    | '/groups/new'
    | '/groups/'
    | '/api/auth/$'
    | '/api/workspaces/members'
    | '/groups/$slug/events'
    | '/groups/$slug/roles'
    | '/groups/$slug/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/home'
    | '/login'
    | '/api/events'
    | '/api/me'
    | '/api/workspaces'
    | '/groups/$slug'
    | '/groups/new'
    | '/groups'
    | '/api/auth/$'
    | '/api/workspaces/members'
    | '/groups/$slug/events'
    | '/groups/$slug/roles'
    | '/groups/$slug/events/new'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/home'
    | '/login'
    | '/api/events'
    | '/api/me'
    | '/api/workspaces'
    | '/groups/$slug'
    | '/groups/new'
    | '/groups/'
    | '/api/auth/$'
    | '/api/workspaces/members'
    | '/groups/$slug_/events'
    | '/groups/$slug_/roles'
    | '/groups/$slug_/events_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiWorkspacesRoute: typeof ApiWorkspacesRouteWithChildren
  GroupsSlugRoute: typeof GroupsSlugRoute
  GroupsNewRoute: typeof GroupsNewRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  GroupsSlugEventsRoute: typeof GroupsSlugEventsRoute
  GroupsSlugRolesRoute: typeof GroupsSlugRolesRoute
  GroupsSlugEventsNewRoute: typeof GroupsSlugEventsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces': {
      id: '/api/workspaces'
      path: '/api/workspaces'
      fullPath: '/api/workspaces'
      preLoaderRoute: typeof ApiWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$slug': {
      id: '/groups/$slug'
      path: '/groups/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof GroupsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/new': {
      id: '/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof GroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces/members': {
      id: '/api/workspaces/members'
      path: '/members'
      fullPath: '/api/workspaces/members'
      preLoaderRoute: typeof ApiWorkspacesMembersRouteImport
      parentRoute: typeof ApiWorkspacesRoute
    }
    '/groups/$slug_/events': {
      id: '/groups/$slug_/events'
      path: '/groups/$slug/events'
      fullPath: '/groups/$slug/events'
      preLoaderRoute: typeof GroupsSlugEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$slug_/roles': {
      id: '/groups/$slug_/roles'
      path: '/groups/$slug/roles'
      fullPath: '/groups/$slug/roles'
      preLoaderRoute: typeof GroupsSlugRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$slug_/events_/new': {
      id: '/groups/$slug_/events_/new'
      path: '/groups/$slug/events/new'
      fullPath: '/groups/$slug/events/new'
      preLoaderRoute: typeof GroupsSlugEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiWorkspacesRouteChildren {
  ApiWorkspacesMembersRoute: typeof ApiWorkspacesMembersRoute
}

const ApiWorkspacesRouteChildren: ApiWorkspacesRouteChildren = {
  ApiWorkspacesMembersRoute: ApiWorkspacesMembersRoute,
}

const ApiWorkspacesRouteWithChildren = ApiWorkspacesRoute._addFileChildren(
  ApiWorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiMeRoute: ApiMeRoute,
  ApiWorkspacesRoute: ApiWorkspacesRouteWithChildren,
  GroupsSlugRoute: GroupsSlugRoute,
  GroupsNewRoute: GroupsNewRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  GroupsSlugEventsRoute: GroupsSlugEventsRoute,
  GroupsSlugRolesRoute: GroupsSlugRolesRoute,
  GroupsSlugEventsNewRoute: GroupsSlugEventsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
